// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VotingSiteAPI.Domain.Entities
{
    using Newtonsoft.Json;

    // BallotTypeMapping
    [Table("BallotTypeMapping", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class BallotTypeMapping
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK_BallotTypeMapping", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // ID (Primary key)

        [Column(@"BallotTypeID", Order = 2, TypeName = "int")]
        [Display(Name = "Ballot type ID")]
        public int? BallotTypeId { get; set; } // BallotTypeID

        [Column(@"ContestID", Order = 3, TypeName = "int")]
        [Display(Name = "Contest ID")]
        public int? ContestId { get; set; } // ContestID

        [Column(@"SortOrder", Order = 4, TypeName = "int")]
        [Display(Name = "Sort order")]
        public int? SortOrder { get; set; } // SortOrder

        // Foreign keys

        /// <summary>
        /// Parent BallotType pointed by [BallotTypeMapping].([BallotTypeId]) (FK_BallotTypeMapping_BallotType)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("BallotTypeId")] public virtual BallotType BallotType { get; set; } // FK_BallotTypeMapping_BallotType

        /// <summary>
        /// Parent Contest pointed by [BallotTypeMapping].([ContestId]) (FK_BallotTypeMapping_Contests)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("ContestId")] public virtual Contest Contest { get; set; } // FK_BallotTypeMapping_Contests
    }

}
// </auto-generated>
