// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VotingSiteAPI.Domain.Entities
{
    using Newtonsoft.Json;

    // Candidates
    [Table("Candidates", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class Candidate
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK_Candidates", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // ID (Primary key)

        [Column(@"ElectionID", Order = 2, TypeName = "int")]
        [Display(Name = "Election ID")]
        public int? ElectionId { get; set; } // ElectionID

        [Column(@"ContestID", Order = 3, TypeName = "int")]
        [Display(Name = "Contest ID")]
        public int? ContestId { get; set; } // ContestID

        [Column(@"CandidateName", Order = 4, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Candidate name")]
        public string CandidateName { get; set; } // CandidateName (length: 50)

        [Column(@"ShortDescription", Order = 5, TypeName = "varchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Short description")]
        public string ShortDescription { get; set; } // ShortDescription (length: 250)

        [Column(@"LongDescription", Order = 6, TypeName = "varchar")]
        [MaxLength(4096)]
        [StringLength(4096)]
        [Display(Name = "Long description")]
        public string LongDescription { get; set; } // LongDescription (length: 4096)

        [Column(@"SortOrder", Order = 7, TypeName = "int")]
        [Display(Name = "Sort order")]
        public int? SortOrder { get; set; } // SortOrder

        [Column(@"CandidateNameRecording", Order = 8, TypeName = "varchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Candidate name recording")]
        public string CandidateNameRecording { get; set; } // CandidateNameRecording (length: 255)

        [Column(@"CandidateBioRecording", Order = 9, TypeName = "varchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Candidate bio recording")]
        public string CandidateBioRecording { get; set; } // CandidateBioRecording (length: 255)

        // Reverse navigation

        /// <summary>
        /// Child Votes where [Votes].[CandidateID] point to this entity (FK_Votes_Candidates)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.List<Vote> Votes { get; set; } = new System.Collections.Generic.List<Vote>(); // Votes.FK_Votes_Candidates

        // Foreign keys

        /// <summary>
        /// Parent Contest pointed by [Candidates].([ContestId]) (FK_Candidates_Contests)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("ContestId")] public virtual Contest Contest { get; set; } // FK_Candidates_Contests
    }

}
// </auto-generated>
