// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VotingSiteAPI.Domain.Entities
{
    using Newtonsoft.Json;

    // Votes
    [Table("Votes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class Vote
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK_Votes", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // ID (Primary key)

        [Column(@"CandidateID", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Candidate ID")]
        public int CandidateId { get; set; } // CandidateID

        [Column(@"VoteDate", Order = 3, TypeName = "datetime")]
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Vote date")]
        public System.DateTime VoteDate { get; set; } // VoteDate

        [Column(@"VoterID", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Voter ID")]
        public int VoterId { get; set; } // VoterID

        // Foreign keys

        /// <summary>
        /// Parent Candidate pointed by [Votes].([CandidateId]) (FK_Votes_Candidates)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("CandidateId"), Required] public virtual Candidate Candidate { get; set; } // FK_Votes_Candidates

        /// <summary>
        /// Parent Voter pointed by [Votes].([VoterId]) (FK_Votes_Voters)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("VoterId"), Required] public virtual Voter Voter { get; set; } // FK_Votes_Voters
    }

}
// </auto-generated>
