// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VotingSiteAPI.Domain.Entities
{
    using Newtonsoft.Json;

    // Voters
    [Table("Voters", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class Voter
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_Voters", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"VoterName", Order = 2, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Voter name")]
        public string VoterName { get; set; } // VoterName (length: 50)

        [Column(@"Affiliation", Order = 3, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Affiliation")]
        public string Affiliation { get; set; } // Affiliation (length: 50)

        [Column(@"ElectionId", Order = 4, TypeName = "int")]
        [Display(Name = "Election ID")]
        public int? ElectionId { get; set; } // ElectionId

        [Column(@"BallotType", Order = 5, TypeName = "int")]
        [Display(Name = "Ballot type")]
        public int? BallotType { get; set; } // BallotType

        [Column(@"LoginId", Order = 6, TypeName = "varchar")]
        [Index(@"LoginId-nc", 1, IsUnique = false, IsClustered = false)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Login ID")]
        public string LoginId { get; set; } // LoginId (length: 50)

        [Column(@"LoginPin", Order = 7, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Login pin")]
        public string LoginPin { get; set; } // LoginPin (length: 50)

        [Column(@"VoteCompleted", Order = 8, TypeName = "bit")]
        [Display(Name = "Vote completed")]
        public bool? VoteCompleted { get; set; } // VoteCompleted

        [Column(@"AccountLockoutExpires", Order = 9, TypeName = "datetime")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Account lockout expires")]
        public System.DateTime? AccountLockoutExpires { get; set; } // AccountLockoutExpires

        // Reverse navigation

        /// <summary>
        /// Child Votes where [Votes].[VoterID] point to this entity (FK_Votes_Voters)
        /// </summary>
        [JsonIgnore]
        public virtual System.Collections.Generic.List<Vote> Votes { get; set; } = new System.Collections.Generic.List<Vote>(); // Votes.FK_Votes_Voters

        // Foreign keys

        /// <summary>
        /// Parent BallotType pointed by [Voters].([BallotType]) (FK_Voters_BallotType)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("BallotType")] public virtual BallotType BallotType_BallotType { get; set; } // FK_Voters_BallotType

        /// <summary>
        /// Parent Election pointed by [Voters].([ElectionId]) (FK_Voters_Elections)
        /// </summary>
        [JsonIgnore]
        [ForeignKey("ElectionId")] public virtual Election Election { get; set; } // FK_Voters_Elections
    }

}
// </auto-generated>
