// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace VotingSiteAPI.Data
{
    using Newtonsoft.Json;
    using VotingSiteAPI.Data.EfCfgMaps;
    using VotingSiteAPI.Domain.Entities;

    public class VotingSiteAPIDbCtxFactory : System.Data.Entity.Infrastructure.IDbContextFactory<VotingSiteAPIDbCtx>
    {
        public VotingSiteAPIDbCtx Create()
        {
            return new VotingSiteAPIDbCtx();
        }
    }
}
// </auto-generated>
