// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace VotingSiteAPI.Data
{
    using Newtonsoft.Json;
    using VotingSiteAPI.Data.EfCfgMaps;
    using VotingSiteAPI.Domain.Entities;

    using System.Linq;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class VotingSiteAPIDbCtx : System.Data.Entity.DbContext, IVotingSiteAPIDbCtx
    {
        public virtual System.Data.Entity.DbSet<BallotType> BallotTypes { get; set; } // BallotType
        public virtual System.Data.Entity.DbSet<BallotTypeMapping> BallotTypeMappings { get; set; } // BallotTypeMapping
        public virtual System.Data.Entity.DbSet<Candidate> Candidates { get; set; } // Candidates
        public virtual System.Data.Entity.DbSet<Contest> Contests { get; set; } // Contests
        public virtual System.Data.Entity.DbSet<Election> Elections { get; set; } // Elections
        public virtual System.Data.Entity.DbSet<LoginAttempt> LoginAttempts { get; set; } // LoginAttempts
        public virtual System.Data.Entity.DbSet<Vote> Votes { get; set; } // Votes
        public virtual System.Data.Entity.DbSet<Voter> Voters { get; set; } // Voters

        static VotingSiteAPIDbCtx()
        {
            System.Data.Entity.Database.SetInitializer<VotingSiteAPIDbCtx>(null);
        }

        public VotingSiteAPIDbCtx()
            : base("Name=VotingSiteConnStr")
        {
        }

        public VotingSiteAPIDbCtx(string connectionString)
            : base(connectionString)
        {
        }

        public VotingSiteAPIDbCtx(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public VotingSiteAPIDbCtx(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public VotingSiteAPIDbCtx(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        public VotingSiteAPIDbCtx(System.Data.Entity.Core.Objects.ObjectContext objectContext, bool dbContextOwnsObjectContext)
            : base(objectContext, dbContextOwnsObjectContext)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new BallotTypeEfConfigMap());
            modelBuilder.Configurations.Add(new BallotTypeMappingEfConfigMap());
            modelBuilder.Configurations.Add(new CandidateEfConfigMap());
            modelBuilder.Configurations.Add(new ContestEfConfigMap());
            modelBuilder.Configurations.Add(new ElectionEfConfigMap());
            modelBuilder.Configurations.Add(new LoginAttemptEfConfigMap());
            modelBuilder.Configurations.Add(new VoteEfConfigMap());
            modelBuilder.Configurations.Add(new VoterEfConfigMap());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new BallotTypeEfConfigMap(schema));
            modelBuilder.Configurations.Add(new BallotTypeMappingEfConfigMap(schema));
            modelBuilder.Configurations.Add(new CandidateEfConfigMap(schema));
            modelBuilder.Configurations.Add(new ContestEfConfigMap(schema));
            modelBuilder.Configurations.Add(new ElectionEfConfigMap(schema));
            modelBuilder.Configurations.Add(new LoginAttemptEfConfigMap(schema));
            modelBuilder.Configurations.Add(new VoteEfConfigMap(schema));
            modelBuilder.Configurations.Add(new VoterEfConfigMap(schema));
            return modelBuilder;
        }
    }
}
// </auto-generated>
