// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VotingSiteAPI.Data.EfCfgMaps
{
    using Newtonsoft.Json;
    using VotingSiteAPI.Data;
    using VotingSiteAPI.Domain.Entities;

    // Candidates
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class CandidateEfConfigMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Candidate>
    {
        public CandidateEfConfigMap()
            : this("dbo")
        {
        }

        public CandidateEfConfigMap(string schema)
        {
            Property(x => x.ElectionId).IsOptional();
            Property(x => x.ContestId).IsOptional();
            Property(x => x.CandidateName).IsOptional().IsUnicode(false);
            Property(x => x.ShortDescription).IsOptional().IsUnicode(false);
            Property(x => x.LongDescription).IsOptional().IsUnicode(false);
            Property(x => x.SortOrder).IsOptional();
            Property(x => x.CandidateNameRecording).IsOptional().IsUnicode(false);
            Property(x => x.CandidateBioRecording).IsOptional().IsUnicode(false);

        }
    }

}
// </auto-generated>
