// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VotingSiteAPI.Data.EfCfgMaps
{
    using Newtonsoft.Json;
    using VotingSiteAPI.Data;
    using VotingSiteAPI.Domain.Entities;

    // Elections
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class ElectionEfConfigMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Election>
    {
        public ElectionEfConfigMap()
            : this("dbo")
        {
        }

        public ElectionEfConfigMap(string schema)
        {
            Property(x => x.ElectionLogoUrl).IsOptional().IsUnicode(false);
            Property(x => x.LoginScreenOpenMessage).IsOptional().IsUnicode(false);
            Property(x => x.LoginScreenCloseMessage).IsOptional().IsUnicode(false);
            Property(x => x.LoginIdLabelTxt).IsOptional().IsUnicode(false);
            Property(x => x.LoginPinLabelTxt).IsOptional().IsUnicode(false);
            Property(x => x.LandingPageTitle).IsOptional().IsUnicode(false);
            Property(x => x.LandingPageMessage).IsOptional().IsUnicode(false);
            Property(x => x.IvrPhoneNumber).IsOptional().IsUnicode(false);
        }
    }

}
// </auto-generated>
