// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VotingSiteAPI.Data.EfCfgMaps
{
    using Newtonsoft.Json;
    using VotingSiteAPI.Data;
    using VotingSiteAPI.Domain.Entities;

    // LoginAttempts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class LoginAttemptEfConfigMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LoginAttempt>
    {
        public LoginAttemptEfConfigMap()
            : this("dbo")
        {
        }

        public LoginAttemptEfConfigMap(string schema)
        {
            Property(x => x.UserIp).IsOptional().IsUnicode(false);
            Property(x => x.BrowserAgent).IsOptional().IsUnicode(false);
            Property(x => x.TimeStamp).IsOptional();
            Property(x => x.EnteredLoginId).IsOptional().IsUnicode(false);
            Property(x => x.SuccessfulLogin).IsOptional();
        }
    }

}
// </auto-generated>
