// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VotingSiteAPI.Data.EfCfgMaps
{
    using Newtonsoft.Json;
    using VotingSiteAPI.Data;
    using VotingSiteAPI.Domain.Entities;

    // Voters
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class VoterEfConfigMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Voter>
    {
        public VoterEfConfigMap()
            : this("dbo")
        {
        }

        public VoterEfConfigMap(string schema)
        {
            Property(x => x.VoterName).IsOptional().IsUnicode(false);
            Property(x => x.Affiliation).IsOptional().IsUnicode(false);
            Property(x => x.ElectionId).IsOptional();
            Property(x => x.BallotType).IsOptional();
            Property(x => x.LoginId).IsOptional().IsUnicode(false);
            Property(x => x.LoginPin).IsOptional().IsUnicode(false);
            Property(x => x.VoteCompleted).IsOptional();

        }
    }

}
// </auto-generated>
